### ISSUE TITLE
postgresql multiple db and users

### ISSUE THREAD

**Issue by dvapelnik** [sameersbn/docker-postgresql#11]
**Can I run container and create two users and two databases on container?**
I want to run GitLab, PostgreSQL, Redis and Redmine setup with single *fig* config. Redmine and GitLab required DB storage. I cant run two postgresql containers for GitLab and Redmine, but I think that this is overhead 
Thanks for reply -)

**Comment by sameersbn** [comment]
@dvapelnik it is possible to add option to create multiple databases (this feature was recently added in my mysql image). It should be possible to add multiple users as well but mapping users to each database might become complicated because there will be multiple use cases like 
- one user and multiple databases
- multiple users and multiple databases
- multiple users and one database (unlikely)

I think adding the option to create multiple databases should be sufficient.

**Comment by sameersbn** [comment]
@dvapelnik I have imported the mysql image feature into the postgresql image. You can now create multiple databases at launch. e.g.

```bash
docker run -it --rm -e 'DB_USER=dbuser' -e 'DB_PASS=dbpass'  -e DB_NAME='db1,db2,db3,db4' sameersbn/postgresql
```

**Comment by dvapelnik** [comment]
thanks for reply and import multiple DB_NAME option for postgresql. it's very usefull!
