### ISSUE TITLE
Application running as user postgres in docker container

### ISSUE THREAD

**Issue by phlegx** [sameersbn/docker-postgresql#56]
Hi Sameer!

First of all, thank you very much for providing this amazing image to us! I just love it!

I would have more of a (general) question which is not really an issue actually. So please if it does not fit here, just feel free to delete it.

Postgres in the container is running as user postgres. On my host I have mapped the volume onto ```/opt/postgresql``` This works just fine and the data can be written onto it, even with the unprivileged postgres user that is running postgres inside the container. I'm wondering how this mechanism works? Since have created my own container with my app inside that runs with an unprivileged user as well and I've mapped  also a volume like ```/opt/myapp``` but in my case writing into that volume with the unprivileged user in the container causes permission denied.

So I'm now wondering what needs to be set to make it behave like your postgres image and other images out there?

thank you very much!

**Comment by sameersbn** [comment]
@phlegx   When the container is started the `entrypoint.sh` script is executed. At this point the effective user is `root`. In the entrypoint script the `create_datadir` function is called which changes the ownership of the `/var/lib/postgresql` directory so that it is owned/writable by the `postgres` user (refer: https://github.com/sameersbn/docker-postgresql/blob/master/runtime/functions#L27-L35). All this is done as the `root` user before starting the server as the `postgres` user.

In your container you will need to change the permissions/ownership of the `/opt/myapp` directory in the entrypoint script.

**Comment by phlegx** [comment]
Thanks a whole lot!

**Comment by sameersbn** [comment]
np
